#!/usr/bin/env python3
"""
Quick Report Validation and File System Test
"""

import json
import os
from datetime import datetime


def validate_existing_reports():
    """Validate existing report files"""
    print("🔍 VALIDATING EXISTING REPORTS")
    print("=" * 40)

    workspace_dir = "workspace"
    if not os.path.exists(workspace_dir):
        print(f"❌ Workspace directory not found: {workspace_dir}")
        return False

    # Find all markdown files
    report_files = []
    for root, dirs, files in os.walk(workspace_dir):
        for file in files:
            if file.endswith(".md"):
                file_path = os.path.join(root, file)
                report_files.append(file_path)

    print(f"📊 Found {len(report_files)} markdown files:")

    valid_reports = 0
    for report_file in report_files:
        file_size = os.path.getsize(report_file)
        print(f"\n📄 {report_file}")
        print(f"  📏 Size: {file_size} bytes")

        if file_size > 0:
            with open(report_file, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            # Analyze content
            lines = content.splitlines()
            words = content.split()
            sections = content.count("#")

            print(f"  📖 Lines: {len(lines)}")
            print(f"  📝 Words: {len(words)}")
            print(f"  🗂️ Sections: {sections}")

            # Quality assessment
            if len(words) > 50 and sections > 0:
                print(f"  ✅ Valid report")
                valid_reports += 1

                # Show first few lines
                preview_lines = lines[:3]
                for i, line in enumerate(preview_lines):
                    if line.strip():
                        print(f"  📖 {line[:80]}...")
                        break
            else:
                print(f"  ⚠️ Empty or minimal content")
        else:
            print(f"  ❌ Empty file")

    print(f"\n📊 Summary: {valid_reports}/{len(report_files)} valid reports")
    return valid_reports > 0


def check_agent_components():
    """Check if agent components are accessible"""
    print("\n🔧 CHECKING AGENT COMPONENTS")
    print("=" * 40)

    try:
        # Test imports
        import sys

        sys.path.append("app")

        print("📦 Testing imports...")

        # Core agent
        from app.agent.manus_core import Manus

        print("  ✅ Manus agent import successful")

        # Configuration
        from app.config import config

        print("  ✅ Configuration import successful")
        print(f"  📁 Workspace root: {config.workspace_root}")
        print(f"  🔧 Max steps: {config.max_steps}")

        # Tools
        from app.tool.browser_use_tool import BrowserUseTool
        from app.tool.python_execute import PythonExecute

        print("  ✅ Tools import successful")

        return True

    except Exception as e:
        print(f"  ❌ Import error: {e}")
        return False


def create_test_report():
    """Create a test report to validate file creation works"""
    print("\n📝 CREATING TEST REPORT")
    print("=" * 40)

    try:
        workspace_dir = "workspace"
        os.makedirs(workspace_dir, exist_ok=True)

        test_report_content = f"""# Test Report - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Purpose
This is a test report to validate that the file system operations are working correctly.

## System Information
- Timestamp: {datetime.now().isoformat()}
- Workspace: {os.path.abspath(workspace_dir)}
- Working Directory: {os.getcwd()}

## Test Results
- File creation: ✅ Working
- Content writing: ✅ Working
- Directory management: ✅ Working

## Validation Checks
1. **File System Access**: Can create files and directories
2. **Content Generation**: Can write structured content
3. **Workspace Management**: Proper file organization

## Conclusion
The core file system functionality is operational and ready for report generation tasks.

---
*Generated by: Test validation script*
*Status: System operational*
"""

        test_file = os.path.join(workspace_dir, "system_validation_test.md")
        with open(test_file, "w", encoding="utf-8") as f:
            f.write(test_report_content)

        print(f"✅ Test report created: {test_file}")
        print(f"📏 Size: {len(test_report_content)} characters")

        # Verify the file
        if os.path.exists(test_file):
            actual_size = os.path.getsize(test_file)
            print(f"📊 Verified size: {actual_size} bytes")
            return True
        else:
            print("❌ File verification failed")
            return False

    except Exception as e:
        print(f"❌ Test report creation failed: {e}")
        return False


def main():
    """Run quick validation tests"""
    print("🚀 QUICK REPORT & SYSTEM VALIDATION")
    print("=" * 50)

    results = {}

    # Test 1: Validate existing reports
    results["existing_reports"] = validate_existing_reports()

    # Test 2: Check agent components
    results["agent_components"] = check_agent_components()

    # Test 3: Create test report
    results["test_report"] = create_test_report()

    # Summary
    print("\n" + "=" * 50)
    print("📋 VALIDATION SUMMARY")
    print("=" * 50)

    passed = sum(1 for result in results.values() if result)
    total = len(results)

    print(f"📊 Results: {passed}/{total} tests passed")

    for test_name, result in results.items():
        status = "✅ PASS" if result else "❌ FAIL"
        print(f"  {status} {test_name.replace('_', ' ').title()}")

    # Final assessment
    if passed == total:
        print("\n🎉 ALL SYSTEMS OPERATIONAL")
        print("✅ Report generation infrastructure working correctly")
        print("✅ Agent components accessible")
        print("✅ File system operations functional")
    elif passed >= total * 0.7:
        print("\n⚠️ MOSTLY OPERATIONAL")
        print("🔧 Minor issues detected but core functionality working")
    else:
        print("\n❌ SIGNIFICANT ISSUES")
        print("🚨 Core functionality problems detected")

    print(f"\n📁 Check the 'workspace' directory for generated reports and test files.")

    return passed >= total * 0.7


if __name__ == "__main__":
    main()
