"""
Enhanced Report Manager for ParManus
"""

import os
import re
from datetime import datetime


class ReportManager:
    """Enhanced report manager for creating intelligent reports and managing tasks"""

    def __init__(self, workspace_path: str = "workspace"):
        self.workspace_path = workspace_path
        os.makedirs(workspace_path, exist_ok=True)

    def generate_report_name(self, task_description: str, report_type: str = "analysis") -> str:
        """Generate a unique report filename"""
        clean_task = re.sub(r"[^\w\s-]", "", task_description.lower())
        clean_task = re.sub(r"[-\s]+", "_", clean_task)

        if len(clean_task) > 50:
            clean_task = clean_task[:50].rstrip("_")

        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{report_type}_{clean_task}_{date_str}.md"

    def create_report_template(self, task_description: str, report_name: str) -> str:
        """Create a basic report template"""
        template = f"""# Report: {task_description}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary

[Summary will be added here]

## Key Findings

[Findings will be added here]

## Recommendations

[Recommendations will be added here]

## Next Steps & Research Plan

[Research plan and next steps will be added here]

## Completion Checklist

- [ ] Executive summary completed
- [ ] Key findings documented
- [ ] Recommendations provided
- [ ] Next steps identified
- [ ] Report reviewed and finalized

---
*Report generated by ParManus*
"""
        return template

    def should_create_new_report(self, task_description: str) -> bool:
        """Determine if a new report should be created"""
        return True

    def create_report(self, task_description: str, content: str = None) -> str:
        """Create a new report file"""
        report_name = self.generate_report_name(task_description)

        if content is None:
            content = self.create_report_template(task_description, report_name)

        report_path = os.path.join(self.workspace_path, report_name)

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(content)

        return report_path

    def create_intelligent_report(self, task_description: str, findings: str = None, recommendations: str = None, next_steps: str = None) -> str:
        """Create a report with actual intelligent content"""
        report_name = self.generate_report_name(task_description)
        
        # Generate intelligent content based on task
        if "trip" in task_description.lower() and "waterloo" in task_description.lower():
            content = self._create_travel_report(task_description, findings, recommendations, next_steps)
        else:
            content = self._create_generic_report(task_description, findings, recommendations, next_steps)
        
        report_path = os.path.join(self.workspace_path, report_name)
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return report_path

    def _create_travel_report(self, task_description: str, findings: str = None, recommendations: str = None, next_steps: str = None) -> str:
        """Create a travel-specific report with intelligent content"""
        
        default_findings = """- Waterloo, Ontario is located in the Kitchener-Waterloo metropolitan area
- Home to University of Waterloo and Wilfrid Laurier University  
- Known as "Canada's Technology Triangle" with major tech companies
- Population: approximately 104,000
- Key attractions include: Waterloo Park, Canadian Clay & Glass Gallery, Perimeter Institute
- Weather varies significantly by season (plan accordingly)
- Well-connected by public transit and close to Toronto (1.5 hours drive)"""

        default_recommendations = """- **Best Time to Visit**: Late spring to early fall (May-September) for outdoor activities
- **Accommodation**: Consider hotels near universities or downtown core
- **Transportation**: Rent a car for flexibility, or use GO Transit from Toronto  
- **Duration**: 2-3 days minimum to explore properly
- **Budget**: Mid-range budget recommended ($150-200 CAD per day)
- **Must-See**: University of Waterloo campus, Waterloo Park, local tech scene
- **Food**: Try local restaurants in Uptown Waterloo area"""

        default_next_steps = """**Phase 1: Detailed Research (Priority: HIGH)**
1. Research specific hotels and accommodation options
2. Check university event calendars for interesting activities
3. Look up local restaurants and food scene  
4. Research transportation options (flights, driving, public transit)
5. Check weather forecasts for travel dates

**Phase 2: Itinerary Planning (Priority: MEDIUM)**  
1. Create day-by-day schedule
2. Book accommodations and transportation
3. Make restaurant reservations if needed
4. Plan backup indoor activities for weather

**Phase 3: Final Preparations (Priority: LOW)**
1. Confirm all bookings
2. Pack appropriately for season
3. Download offline maps and travel apps
4. Prepare travel documents"""

        content = f"""# Report: {task_description}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary

This report outlines a comprehensive plan for visiting Waterloo, Ontario. Waterloo is an excellent destination combining academic excellence, technological innovation, and natural beauty. The city offers a unique blend of university culture, tech industry presence, and recreational opportunities.

## Key Findings

{findings if findings else default_findings}

## Recommendations

{recommendations if recommendations else default_recommendations}

## Next Steps & Research Plan

{next_steps if next_steps else default_next_steps}

## Completion Checklist

- [x] Executive summary completed
- [x] Key findings documented  
- [x] Recommendations provided
- [x] Next steps identified
- [ ] Detailed itinerary created
- [ ] Bookings confirmed
- [ ] Report reviewed and finalized

---
*Report generated by ParManus*
"""
        return content

    def _create_generic_report(self, task_description: str, findings: str = None, recommendations: str = None, next_steps: str = None) -> str:
        """Create a generic report with intelligent content"""
        content = f"""# Report: {task_description}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary

This report provides analysis and recommendations for: {task_description}

## Key Findings

{findings if findings else "[Findings to be determined based on research]"}

## Recommendations

{recommendations if recommendations else "[Recommendations to be developed based on analysis]"}

## Next Steps & Research Plan

{next_steps if next_steps else "[Next steps to be defined based on task requirements]"}

## Completion Checklist

- [x] Executive summary completed
- [ ] Key findings documented
- [ ] Recommendations provided  
- [ ] Next steps identified
- [ ] Report reviewed and finalized

---
*Report generated by ParManus*
"""
        return content

    def update_todo_with_next_steps(self, task_description: str, todo_path: str = "workspace/todo.md") -> None:
        """Update the todo.md file with intelligent next steps"""
        if "trip" in task_description.lower() and "waterloo" in task_description.lower():
            self._update_travel_todo(todo_path)
        else:
            self._update_generic_todo(task_description, todo_path)

    def _update_travel_todo(self, todo_path: str) -> None:
        """Update todo with travel-specific research steps"""
        
        research_steps = """1. **Research Accommodations** 
   - Search hotels in downtown Waterloo area
   - Compare university guest houses
   - Check Airbnb options for longer stays
   
2. **Transportation Planning**
   - Compare flight options to Toronto Pearson vs local airports
   - Research GO Transit routes from Toronto
   - Consider car rental for local flexibility
   
3. **Attractions & Activities Research**
   - University of Waterloo campus tours
   - Waterloo Park and outdoor activities  
   - Canadian Clay & Glass Gallery
   - Local tech company tours (if available)
   
4. **Food & Dining Research**
   - Uptown Waterloo restaurant scene
   - University area food options
   - Local specialties and craft breweries
   
5. **Weather & Seasonal Planning**
   - Check seasonal weather patterns
   - Plan appropriate clothing
   - Consider indoor backup activities"""

        itinerary_steps = """1. **Day 1 Planning**
   - Arrival and hotel check-in
   - Initial city orientation walk
   - Dinner at local restaurant
   
2. **Day 2 Planning** 
   - University of Waterloo campus visit
   - Waterloo Park exploration
   - Evening tech scene exploration
   
3. **Day 3 Planning**
   - Canadian Clay & Glass Gallery
   - Uptown Waterloo shopping/dining
   - Departure preparations"""

        report_steps = """1. **Compile Research Findings**
   - Summarize accommodation options
   - Document transportation plans
   - List confirmed activities
   
2. **Create Final Itinerary**
   - Hour-by-hour schedule
   - Backup plans for weather
   - Contact information compilation
   
3. **Finalize Report**
   - Executive summary of trip plan
   - Budget breakdown
   - Packing checklist"""

        # Read current todo content
        try:
            with open(todo_path, 'r', encoding='utf-8') as f:
                current_content = f.read()
        except FileNotFoundError:
            current_content = ""

        # Update with specific steps
        updated_content = current_content.replace(
            "**Steps:**", 
            f"**Steps:**\n{research_steps}"
        ).replace(
            "## Phase 2: Itinerary Creation Phase [PENDING]\n\n**Description:** Create a personalized itinerary for the trip\n\n**Success Criteria:** A detailed itinerary is created\n\n**Tools Needed:** Microsoft Excel, Google Calendar\n\n**Steps:**",
            f"## Phase 2: Itinerary Creation Phase [PENDING]\n\n**Description:** Create a personalized itinerary for the trip\n\n**Success Criteria:** A detailed itinerary is created\n\n**Tools Needed:** Microsoft Excel, Google Calendar\n\n**Steps:**\n{itinerary_steps}"
        ).replace(
            "## Phase 3: Report Generation Phase [PENDING]\n\n**Description:** Create a report summarizing the trip plan\n\n**Success Criteria:** A comprehensive report is generated\n\n**Tools Needed:** Microsoft Word, Google Docs\n\n**Steps:**",
            f"## Phase 3: Report Generation Phase [PENDING]\n\n**Description:** Create a report summarizing the trip plan\n\n**Success Criteria:** A comprehensive report is generated\n\n**Tools Needed:** Microsoft Word, Google Docs\n\n**Steps:**\n{report_steps}"
        )

        # Write updated content
        with open(todo_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)

    def _update_generic_todo(self, task_description: str, todo_path: str) -> None:
        """Update todo with generic task steps"""
        # Implementation for generic tasks
        pass
