"""
Todo Manager
Handles creation and management of todo.md files
"""

import os
from typing import Dict

from app.config import config
from app.logger import logger


class TodoManager:
    """
    Manages todo file creation, updates, and progress tracking
    """

    def __init__(self):
        self.todo_file_path = os.path.join(config.workspace_root, "todo.md")

    async def create_todo_from_plan(self, plan: Dict) -> None:
        """
        Create a detailed todo.md file from the LLM-generated plan
        """
        logger.info("📝 Creating detailed todo list from LLM plan")

        todo_content = f"""# 📋 Task Execution Plan

## 🎯 Goal
**{plan.get('goal', 'No goal specified')}**

## 📊 Task Details
- **Type:** {plan.get('task_type', 'general')}
- **Complexity:** {plan.get('complexity', 'unknown')}
- **Priority:** {plan.get('priority', 'medium')}
- **Estimated Duration:** {plan.get('estimated_duration', 'unknown')}
- **Created:** {plan.get('created_at', 'unknown')}

## 🏆 Final Deliverable
{plan.get('final_deliverable', 'Task completion')}

## ✅ Success Criteria
{plan.get('success_criteria', 'User satisfaction')}

---

"""

        # Add phases and steps
        phases = plan.get("phases", [])
        for i, phase in enumerate(phases):
            todo_content += f"""## Phase {phase.get('id', i+1)}: {phase.get('title', 'Unnamed Phase')}

**Description:** {phase.get('description', 'No description')}

**Estimated Time:** {phase.get('estimated_time', 'unknown')}

**Tools Needed:** {', '.join(phase.get('tools_needed', ['None']))}

**Success Criteria:** {phase.get('success_criteria', 'Complete all steps')}

### 📝 Steps:
"""

            steps = phase.get("steps", [])
            for j, step in enumerate(steps, 1):
                todo_content += f"{j}. [ ] {step}\n"

            todo_content += "\n---\n\n"

        # Add progress tracking section
        todo_content += """## 📈 Progress Tracking

### Current Status
- [ ] Planning Complete
- [ ] Execution Started
- [ ] Phase 1 Complete
- [ ] Phase 2 Complete
- [ ] All Phases Complete
- [ ] Final Review
- [ ] Task Complete

### Notes
(Add notes and observations here as the task progresses)

---

*Generated by LLM-Driven Planning System*
"""

        # Write to file
        try:
            with open(self.todo_file_path, "w", encoding="utf-8") as f:
                f.write(todo_content)

            logger.info(f"📝 Todo list saved to {self.todo_file_path}")

        except Exception as e:
            logger.warning(f"Failed to save todo list: {e}")

    async def update_todo_progress(self, completed_step: str) -> None:
        """
        Update the todo list with completed steps
        """
        try:
            if not os.path.exists(self.todo_file_path):
                return

            with open(self.todo_file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Mark step as completed
            updated_content = content.replace(
                f"[ ] {completed_step}", f"[x] {completed_step}"
            )

            with open(self.todo_file_path, "w", encoding="utf-8") as f:
                f.write(updated_content)

            logger.info(f"✅ Marked step as complete: {completed_step}")

        except Exception as e:
            logger.warning(f"Failed to update todo progress: {e}")

    async def get_current_plan_status(self) -> Dict:
        """
        Get the current status of the plan from the todo file
        """
        try:
            if not os.path.exists(self.todo_file_path):
                return {"status": "no_plan", "message": "No todo file found"}

            with open(self.todo_file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Count completed vs total steps
            total_checkboxes = content.count("[ ]") + content.count("[x]")
            completed_checkboxes = content.count("[x]")

            if total_checkboxes == 0:
                progress = 0
            else:
                progress = (completed_checkboxes / total_checkboxes) * 100

            return {
                "status": "active",
                "progress": round(progress, 1),
                "completed_steps": completed_checkboxes,
                "total_steps": total_checkboxes,
                "message": f"Progress: {completed_checkboxes}/{total_checkboxes} steps completed ({progress:.1f}%)",
            }

        except Exception as e:
            logger.warning(f"Failed to get plan status: {e}")
            return {"status": "error", "message": str(e)}

    def get_todo_file_path(self) -> str:
        """Get the path to the todo file"""
        return self.todo_file_path
