"""
Hallucination Detector for Manus Agent Tools

This module provides comprehensive detection and handling of LLM-generated
hallucinations, particularly fake URLs, non-existent endpoints, and invalid
parameters that could cause tool execution failures.
"""

import asyncio
import re
import socket
from typing import Any, Dict, List, Optional, Set, Tuple
from urllib.parse import urljoin, urlparse

import aiohttp

from app.logger import logger


class HallucinationDetector:
    """
    Advanced hallucination detector for LLM-generated parameters and URLs.

    Detects and handles:
    - Fake URLs and domains
    - Non-existent endpoints
    - Invalid API parameters
    - Suspicious patterns in LLM outputs
    """

    def __init__(self):  # Known fake/hallucinated domains commonly generated by LLMs
        self.known_fake_domains = {
            "elonmusk.com",
            "example-api.com",
            "test-website.com",
            "sample-site.com",
            "demo-api.org",
            "placeholder.com",
            "fake-api.net",
            "mock-service.io",
            "dummy-site.org",
            "test-endpoint.com",
        }  # Known legitimate domains to never flag as hallucinations
        self.known_legitimate_domains = {
            "google.com",
            "google.co.uk",
            "google.ca",
            "google.au",
            "bing.com",
            "duckduckgo.com",
            "microsoft.com",
            "github.com",
            "stackoverflow.com",
            "wikipedia.org",
            "reddit.com",
            "twitter.com",
            "youtube.com",
            "linkedin.com",
            "facebook.com",
            "instagram.com",
            "news.ycombinator.com",
            "medium.com",
            "techcrunch.com",
            "wired.com",
            "theverge.com",
            "arstechnica.com",
            "bbc.com",
            "cnn.com",
            "reuters.com",
            "bloomberg.com",
            "wsj.com",
            "nytimes.com",
            "washingtonpost.com",
            "coindesk.com",
            "coinbase.com",
            "binance.com",
            "tesla.com",
            "spacex.com",
            "httpbin.org",
            "python.org",
            "httpbin.org",
            "wikipedia.org",
            "amazon.com",
            "facebook.com",
            "twitter.com",
            "linkedin.com",
            "youtube.com",
            "instagram.com",
            "reddit.com",
            "openai.com",
            "anthropic.com",
        }  # Common hallucinated URL patterns (made more specific to avoid false positives)
        self.suspicious_patterns = [
            r"https?://www\.[a-z-]{3,8}\.com/?$",  # Simple www.shortname.com patterns (3-8 chars only)
            r"https?://api\.[a-z-]{3,8}\.com/?$",  # Simple api.shortname.com patterns (3-8 chars only)
            r"https?://[a-z-]+\.example\.com",  # example.com subdomains
            r"https?://localhost:\d+/api/",  # Localhost API endpoints
            r"https?://127\.0\.0\.1:\d+/",  # Local IP endpoints
            r"https?://test[a-z-]*\.com/?$",  # test*.com domains
            r"https?://demo[a-z-]*\.com/?$",  # demo*.com domains
            r"https?://fake[a-z-]*\.com/?$",  # fake*.com domains
        ]

        # Cache for URL validation results to avoid repeated checks
        self.url_validation_cache: Dict[str, bool] = {}

        # Session for HTTP checks
        self.session: Optional[aiohttp.ClientSession] = None

    async def __aenter__(self):
        """Async context manager entry."""
        self.session = aiohttp.ClientSession(
            timeout=aiohttp.ClientTimeout(total=5),
            connector=aiohttp.TCPConnector(limit=10),
        )
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        if self.session:
            await self.session.close()

    def detect_hallucinated_parameters(
        self, tool_name: str, parameters: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Main detection method for hallucinated parameters.

        Args:
            tool_name: Name of the tool being called
            parameters: Dictionary of parameters to validate

        Returns:
            Dictionary with detection results:
            {
                'is_hallucination': bool,
                'detected_issues': List[str],
                'corrected_parameters': Dict[str, Any],
                'confidence': float
            }
        """
        logger.info(f"🔍 Hallucination detector analyzing {tool_name} parameters")

        detection_result = {
            "is_hallucination": False,
            "detected_issues": [],
            "corrected_parameters": parameters.copy(),
            "confidence": 0.0,
        }

        # URL-specific detection for browser tools
        if tool_name in ["enhanced_browser", "browser_use", "web_search"]:
            url_result = self._detect_hallucinated_urls(parameters)
            if url_result["is_hallucination"]:
                detection_result.update(url_result)

        # Parameter pattern detection
        pattern_result = self._detect_suspicious_patterns(parameters)
        if pattern_result["is_hallucination"]:
            detection_result["is_hallucination"] = True
            detection_result["detected_issues"].extend(
                pattern_result["detected_issues"]
            )
            detection_result["confidence"] = max(
                detection_result["confidence"], pattern_result["confidence"]
            )

        # Domain validation
        domain_result = self._validate_domains(parameters)
        if domain_result["is_hallucination"]:
            detection_result["is_hallucination"] = True
            detection_result["detected_issues"].extend(domain_result["detected_issues"])
            detection_result["confidence"] = max(
                detection_result["confidence"], domain_result["confidence"]
            )

        if detection_result["is_hallucination"]:
            logger.warning(
                f"🚨 Hallucination detected in {tool_name}: {detection_result['detected_issues']}"
            )
        else:
            logger.info(f"✅ No hallucinations detected in {tool_name} parameters")

        return detection_result

    def _detect_hallucinated_urls(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Detect hallucinated URLs in parameters."""
        result = {
            "is_hallucination": False,
            "detected_issues": [],
            "corrected_parameters": parameters.copy(),
            "confidence": 0.0,
        }

        # Check common URL parameter names
        url_params = ["url", "website", "link", "endpoint", "target_url", "base_url"]

        for param_name in url_params:
            if param_name in parameters:
                url = str(parameters[param_name])
                url_check = self._validate_url(url)

                if url_check["is_suspicious"]:
                    result["is_hallucination"] = True
                    result["detected_issues"].append(
                        f"Suspicious URL in {param_name}: {url}"
                    )
                    result["confidence"] = max(
                        result["confidence"], url_check["confidence"]
                    )  # Try to provide a corrected URL
                    if url_check["suggested_correction"]:
                        result["corrected_parameters"][param_name] = url_check[
                            "suggested_correction"
                        ]

        return result

    def _validate_url(self, url: str) -> Dict[str, Any]:
        """Validate a single URL for hallucination indicators."""
        if not url or not isinstance(url, str):
            return {
                "is_suspicious": False,
                "confidence": 0.0,
                "suggested_correction": None,
            }

        # Check cache first
        if url in self.url_validation_cache:
            return {
                "is_suspicious": not self.url_validation_cache[url],
                "confidence": 0.8 if not self.url_validation_cache[url] else 0.0,
                "suggested_correction": None,
            }

        try:
            parsed = urlparse(url)
            domain = parsed.netloc.lower()
            # Remove www. prefix for checking
            if domain.startswith("www."):
                domain = domain[4:]

            # ALWAYS allow search engine URLs and never flag them as suspicious
            if self._is_search_engine_url(url, domain):
                logger.debug(f"✅ Search engine URL allowed: {url}")
                return {
                    "is_suspicious": False,
                    "confidence": 0.0,
                    "suggested_correction": None,
                }

            # Check if it's a known legitimate domain
            if domain in self.known_legitimate_domains:
                return {
                    "is_suspicious": False,
                    "confidence": 0.0,
                    "suggested_correction": None,
                }

            # Check against known fake domains
            if domain in self.known_fake_domains:
                logger.warning(f"🎭 Known fake domain detected: {domain}")
                return {
                    "is_suspicious": True,
                    "confidence": 0.95,
                    "suggested_correction": self._suggest_real_alternative(domain),
                }

            # Check suspicious patterns (but skip search engines)
            for pattern in self.suspicious_patterns:
                if re.match(pattern, url, re.IGNORECASE):
                    # Double-check it's not a search engine URL before flagging
                    if not self._is_search_engine_url(url, domain):
                        logger.warning(f"🎯 Suspicious URL pattern detected: {url}")
                        return {
                            "is_suspicious": True,
                            "confidence": 0.7,
                            "suggested_correction": self._suggest_real_alternative(
                                domain
                            ),
                        }

            # Check for obviously fake patterns
            if self._is_obviously_fake_url(url):
                return {
                    "is_suspicious": True,
                    "confidence": 0.9,
                    "suggested_correction": self._suggest_real_alternative(domain),
                }

            return {
                "is_suspicious": False,
                "confidence": 0.0,
                "suggested_correction": None,
            }

        except Exception as e:
            logger.warning(f"URL validation error for {url}: {e}")
            return {
                "is_suspicious": True,
                "confidence": 0.6,
                "suggested_correction": None,
            }

    def _is_search_engine_url(self, url: str, domain: str) -> bool:
        """Check if URL is a legitimate search engine URL that should never be flagged."""
        # Known search engine domains
        search_domains = {
            "google.com",
            "google.co.uk",
            "google.ca",
            "google.au",
            "google.de",
            "google.fr",
            "bing.com",
            "duckduckgo.com",
            "yandex.com",
            "baidu.com",
            "yahoo.com",
        }

        # Check if it's a search engine domain
        if domain in search_domains:
            return True

        # Check for search engine subdomains
        for search_domain in search_domains:
            if domain.endswith(f".{search_domain}"):
                return True

        # Check for specific search URL patterns
        search_patterns = [
            r"google\.(com|co\.uk|ca|au|de|fr)/search",
            r"bing\.com/search",
            r"duckduckgo\.com/",
            r"yahoo\.com/search",
            r"yandex\.(com|ru)/search",
        ]

        for pattern in search_patterns:
            if re.search(pattern, url, re.IGNORECASE):
                return True

        return False

    def _is_obviously_fake_url(self, url: str) -> bool:
        """Check for obviously fake URL patterns."""
        fake_indicators = [
            "elonmusk.com",  # Specific case we're seeing
            "example.com",
            "test.com",
            "demo.com",
            "sample.com",
            "placeholder.com",
            "fake.com",
            "mock.com",
            "dummy.com",
        ]

        url_lower = url.lower()
        return any(indicator in url_lower for indicator in fake_indicators)

    def _suggest_real_alternative(self, fake_domain: str) -> str:
        """Suggest real alternatives for fake domains."""
        alternatives = {
            "elonmusk.com": "https://twitter.com/elonmusk",
            "example.com": "https://httpbin.org",
            "test.com": "https://httpbin.org",
            "demo.com": "https://httpbin.org",
            "sample.com": "https://httpbin.org",
        }

        return alternatives.get(fake_domain, "https://httpbin.org")

    def _detect_suspicious_patterns(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Detect suspicious patterns in parameter values."""
        result = {"is_hallucination": False, "detected_issues": [], "confidence": 0.0}

        # Check for placeholder-like values
        placeholder_patterns = [
            r"^(your_|my_|test_|demo_|sample_)",
            r"^(example|placeholder|dummy|fake|mock)$",  # Only match these as complete words
            r"^(xxx|aaa|bbb|ccc)$",
            r"^\d{4}-\d{2}-\d{2}$",  # Date patterns that might be placeholders
        ]

        for param_name, value in parameters.items():
            if isinstance(value, str):
                # Skip pattern checking for search engine URLs
                if param_name == "url" and self._is_search_engine_url_param(value):
                    continue

                for pattern in placeholder_patterns:
                    if re.search(pattern, value, re.IGNORECASE):
                        result["is_hallucination"] = True
                        result["detected_issues"].append(
                            f"Placeholder-like value in {param_name}: {value}"
                        )
                        result["confidence"] = max(result["confidence"], 0.6)

        return result

    def _is_search_engine_url_param(self, url_param: str) -> bool:
        """Check if a URL parameter is for a search engine."""
        try:
            parsed = urlparse(url_param)
            domain = parsed.netloc.lower()
            if domain.startswith("www."):
                domain = domain[4:]
            return self._is_search_engine_url(url_param, domain)
        except:
            return False

    def _validate_domains(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Validate domains in parameters."""
        result = {"is_hallucination": False, "detected_issues": [], "confidence": 0.0}

        # Extract potential domains from all string parameters
        for param_name, value in parameters.items():
            if isinstance(value, str) and ("http" in value or "." in value):
                domains = self._extract_domains_from_text(value)
                for domain in domains:
                    if domain in self.known_fake_domains:
                        result["is_hallucination"] = True
                        result["detected_issues"].append(
                            f"Known fake domain in {param_name}: {domain}"
                        )
                        result["confidence"] = max(result["confidence"], 0.8)

        return result

    def _extract_domains_from_text(self, text: str) -> Set[str]:
        """Extract domain names from text."""
        domains = set()

        # Extract URLs and get their domains
        url_pattern = r"https?://([^/\s]+)"
        urls = re.findall(url_pattern, text)
        for url in urls:
            domain = url.lower()
            if domain.startswith("www."):
                domain = domain[4:]
            domains.add(domain)

        # Extract domain-like patterns
        domain_pattern = r"\b([a-z0-9-]+\.(?:com|org|net|io|co|edu|gov))\b"
        domain_matches = re.findall(domain_pattern, text, re.IGNORECASE)
        domains.update(d.lower() for d in domain_matches)

        return domains

    async def validate_url_accessibility(self, url: str) -> bool:
        """
        Asynchronously validate if a URL is accessible.

        Args:
            url: URL to validate

        Returns:
            True if URL is accessible, False otherwise
        """
        if not self.session:
            # If no session, do basic validation only
            return not self._validate_url(url)["is_suspicious"]

        try:
            # Check if we've already validated this URL
            if url in self.url_validation_cache:
                return self.url_validation_cache[url]

            # Try to access the URL with a HEAD request
            async with self.session.head(url, allow_redirects=True) as response:
                is_accessible = response.status < 400
                self.url_validation_cache[url] = is_accessible
                return is_accessible

        except Exception as e:
            logger.debug(f"URL accessibility check failed for {url}: {e}")
            self.url_validation_cache[url] = False
            return False

    def generate_safe_alternative(
        self, tool_name: str, original_params: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate safe alternative parameters when hallucination is detected.

        Args:
            tool_name: Name of the tool
            original_params: Original parameters with hallucinations

        Returns:
            Safe alternative parameters
        """
        safe_params = original_params.copy()  # Browser tool alternatives
        if tool_name in ["enhanced_browser", "browser_use", "web_search"]:
            if "url" in safe_params:
                url = str(safe_params["url"])
                parsed = urlparse(url)
                domain = parsed.netloc.lower()
                if domain.startswith("www."):
                    domain = domain[4:]

                # NEVER replace search engine URLs - they are legitimate
                if self._is_search_engine_url(url, domain):
                    logger.info(f"✅ Preserving search engine URL: {url}")
                elif self._validate_url(url)["is_suspicious"]:
                    # Only replace truly suspicious URLs, not search engines
                    safe_params["url"] = "https://httpbin.org/get"
                    logger.info(
                        f"🔄 Replaced suspicious URL with safe alternative: {safe_params['url']}"
                    )

        # Add safe mode flags
        safe_params["_hallucination_detected"] = True
        safe_params["_safe_mode"] = True

        return safe_params

    def log_detection_summary(self, detections: List[Dict[str, Any]]):
        """Log a summary of all detections."""
        if not detections:
            logger.info("🎯 Hallucination detector: No issues detected in this session")
            return

        total_detections = len([d for d in detections if d.get("is_hallucination")])
        if total_detections > 0:
            logger.warning(
                f"🚨 Hallucination detector found {total_detections} potential issues:"
            )
            for detection in detections:
                if detection.get("is_hallucination"):
                    for issue in detection.get("detected_issues", []):
                        logger.warning(f"  • {issue}")
        else:
            logger.info("✅ All parameters validated successfully")


# Global instance for easy access
hallucination_detector = HallucinationDetector()
